package com.distributed.store.metadata;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class ClusterLauncher {

    private static final List<Process> runningProcesses = new ArrayList<>();
    private static final String LOG_DIR = "logs";
    private static final String CONFIG_FILE = "cluster.properties";

    public static void main(String[] args) throws IOException, InterruptedException {
        setupDirectories();

        // 1. Configuration Data
        // Structure: { Port, NodeID }
        // Note: Peers are derived automatically in the config file generation
        String[][] nodeConfigs = {
                {"9001", "Node_A"},
                {"9002", "Node_B"},
                {"9003", "Node_C"}
        };

        // 2. Generate the shared 'cluster.properties' file
        System.out.println("--- GENERATING CONFIG ---");
        generateConfigFile(nodeConfigs);

        // 3. Shutdown Hook
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("\n[Launcher] Shutting down all nodes...");
            for (Process p : runningProcesses) {
                if (p.isAlive()) p.destroyForcibly();
            }
            System.out.println("[Launcher] All nodes terminated.");
        }));

        System.out.println("--- STARTING CLUSTER (IPv4 Forced) ---");
        System.out.println("Logs: " + new File(LOG_DIR).getAbsolutePath());
        System.out.println("Config: " + new File(CONFIG_FILE).getAbsolutePath());

        // 4. Launch Nodes
        for (String[] config : nodeConfigs) {
            String nodeId = config[1];

            System.out.printf("Launching %s... ", nodeId);
            try {
                // Pass NodeID and the Config File Path
                runningProcesses.add(startNode(nodeId, CONFIG_FILE));
                System.out.println("[OK]");
            } catch (IOException e) {
                System.out.println("[FAILED]");
                e.printStackTrace();
            }

            Thread.sleep(500); // Stagger start
        }

        System.out.println("--- CLUSTER RUNNING ---");
        System.out.println("Type 'exit' to stop.");

        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine().trim();
            if ("exit".equalsIgnoreCase(line)) break;
            if ("status".equalsIgnoreCase(line)) printStatus();
        }
        System.exit(0);
    }

    /**
     * Generates a standard properties file that ClusterConfig can read.
     * Output format:
     * node.Node_A=localhost:9001
     * node.Node_B=localhost:9002
     */
    private static void generateConfigFile(String[][] configs) throws IOException {
        try (PrintWriter writer = new PrintWriter(new FileWriter(CONFIG_FILE))) {
            writer.println("# Auto-generated by ClusterLauncher");
            for (String[] config : configs) {
                String port = config[0];
                String nodeId = config[1];
                // Assuming localhost for local cluster testing
                writer.println("node." + nodeId + "=localhost:" + port);
            }
        }
        System.out.println("Generated " + CONFIG_FILE);
    }

    private static Process startNode(String nodeId, String configFilePath) throws IOException {
        String javaHome = System.getProperty("java.home");
        String javaBin = javaHome + File.separator + "bin" + File.separator + "java";
        String classpath = System.getProperty("java.class.path");
        String className = MetadataServer.class.getName();

        List<String> command = new ArrayList<>();
        command.add(javaBin);

        // --- JVM FLAGS ---
        command.add("-Djava.net.preferIPv4Stack=true");
        command.add("-ea"); // Enable Assertions
        command.add("-Dio.netty.leakDetection.level=disabled");

        command.add("-cp");
        command.add(classpath);
        command.add(className);

        // --- APPLICATION ARGS ---
        // Matches MetadataServer.main(String[] args)
        command.add(nodeId);         // args[0]
        command.add(configFilePath); // args[1]

        ProcessBuilder builder = new ProcessBuilder(command);

        // --- LOGGING ---
        File logFile = new File(LOG_DIR, nodeId + ".log");
        builder.redirectOutput(ProcessBuilder.Redirect.appendTo(logFile));
        builder.redirectError(ProcessBuilder.Redirect.appendTo(logFile));

        return builder.start();
    }

    private static void setupDirectories() throws IOException {
        if (!Files.exists(Paths.get(LOG_DIR))) {
            Files.createDirectories(Paths.get(LOG_DIR));
        }
    }

    private static void printStatus() {
        long aliveCount = runningProcesses.stream().filter(Process::isAlive).count();
        System.out.println("[Status] " + aliveCount + "/" + runningProcesses.size() + " nodes are alive.");
    }
}